apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 2
  selector:
   matchLabels:
     app: library-app
  template:
   metadata:
     labels:
       app: library-app
     annotations:
       ad.datadoghq.com/library-app.logs: '[{"source":"nodejs","service":"library-service"},{"source":"nodejs","service":"library-app"}]'
   spec:
     containers:
     - name: library-app
       image: tejaswinikandimalla/library-app:latest
       ports:
       - containerPort: 3000
       env:
       - name: MONGODB_URI
         value: "mongodb://localhost:27017/parceltracker"
       - name: PORT
         value: "3000"
       - name: HOST
         value: "0.0.0.0"
       - name: NODE_ENV
         value: "production"
       # Datadog APM (tracing) env variables
       - name: DD_AGENT_HOST
         valueFrom:
           fieldRef:
             fieldPath: status.hostIP
       - name: DD_TRACE_AGENT_PORT
         value: "8126"
       - name: DD_ENV
         value: "production"
       - name: DD_SERVICE
         value: "Library-app"
       - name: DD_VERSION
         value: "1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
   app: library-app
  ports:
  - port: 8070
    targetPort: 3000
  type: LoadBalancer
 